image: node:latest

# first, install Cypress, then run all tests (in parallel)
stages:
  - prepare
  - build
  - test

# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

# this job installs NPM dependencies and Cypress
cypress:
  image: cypress/base:10
  stage: build
  script:
    - cd .. && npm init

IHM:
  stage: build
  script:
    - git clone https://github.com/mspr-ci/API.git

API:
  stage: build
  script:
    - git clone https://github.com/mspr-ci/IHM.git
