image: gradle:jdk11

stages:
  - test
  - build

before_script:
  - wget -qO- https://deb.nodesource.com/setup_12.x | bash -
  - apt install -y nodejs

test:
  stage: test
  script: gradle test
  artifacts:
    name: "jacocoTestReport"
    paths:
    - build/reports/jacoco/test/jacocoTestReport.xml

integration_test:
  stage: test
  script: gradle integrationTest jacocoTestReport
  artifacts:
    name: "jacocoIntegrationTestReport"
    paths:
    - build/reports/jacoco/test/jacocoTestReport.xml

linter:
  stage: test
  script:
    - gradle sonarqube

build:
  stage: build
  script: gradle -Pprod clean bootJar

cache:
  paths: [node_modules/]
