image: gradle:jdk11

stages:
  - test
  - build

before_script:
  - wget -qO- https://deb.nodesource.com/setup_12.x | bash -
  - apt install -y nodejs

test:
  stage: test
  script: gradle test integrationTest jacocoTestReport 
  artifacts:
    name: "jacocoTestReport"
    paths:
    - build/reports/jacoco/test/jacocoTestReport.xml
coveralls:
  stage: test
  script: gradle coveralls
  dependencies:
    - test

linter:
  stage: test
  script:
    - gradle sonarqube

build:
  stage: build
  script: gradle -Pprod clean bootJar

cache:
  paths: [node_modules/]
