image: gradle:jdk11

stages:
  - test
  - build
  
before_script:
  - wget -qO- https://deb.nodesource.com/setup_12.x | bash -
  - apt install -y nodejs

test:
  stage: test
  script: gradle test
  cache:
    paths: [node_modules/]
  
linter:
  stage: test
  script:
    - gradle sonarqube

build:
  stage: build
  scripts: gradle -Pprod clean bootJar
