image: gradle:jdk11

stages:
  - test
  - build

before_script:
  - wget -qO- https://deb.nodesource.com/setup_12.x | bash -
  - apt install -y nodejs

test:
  stage: test
  script: gradle test

integration_test:
  stage: test
  script: gradle integrationTest

linter:
  stage: test
  script:
    - gradle sonarqube

build:
  stage: build
  script: gradle -Pprod clean bootJar

cache:
  paths: [node_modules/]
