image: gradle:jdk11

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: gradle test integrationTest jacocoTestReport
  artifacts:
    name: "jacocoTestReport"
    paths:
      - build/reports/jacoco/test/jacocoTestReport.xml

coveralls:test:
  stage: test
  script: gradle coveralls

build:
  stage: build
  script: gradle -Pprod clean bootJar

deploy production:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master

deploy staging:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - staging


