image: gradle:jdk11

stages:
  - test
  - build

test:
  stage: test
  script: gradle test integrationTest jacocoTestReport
  artifacts:
    name: "jacocoTestReport"
    paths:
      - build/reports/jacoco/test/jacocoTestReport.xml

  coveralls:
    stage: test
    script: gradle coveralls

build:
  stage: build
  script: gradle -Pprod clean bootJar


