
image: node:alpine

stages:
  - setup
  - prepare
  - test
  - version
  - build
  - deploy

setup:
  stage: setup
  script:
    - npm ci
  only:
    - master

install packages:
  stage: prepare
  script:
    - echo 1

run linter:
  stage: test
  script:
    - echo 1

run tests:
  stage: test
  script:
    - npm run test:unit

execute coverage:
  stage: test
  script:
    - echo 1

run sonar:
  stage: test
  script:
    - echo 1

next minor:
  stage: version
  script:
    - echo 1

next release:
  stage: version
  script:
    - echo 1

build package:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - master

build image:
  stage: build
  script:
    - echo 1

deploy production:
  stage: deploy
  script:
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  only:
    - master

deploy staging:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - staging

deploy branch:
  stage: deploy
  script:
    - echo 1
