image: node:alpine

stages:
  - setup
  - prepare
  - test
  - quality
  - version
  - build
  - deploy

setup:
  stage: setup
  script:
    - npm ci
  only:
    - master

install packages:
  stage: prepare
  script:
    - npm install

run tests:
  stage: test
  script:
    - npm run test

execute coverage:
  stage: test
  script:
    - echo 1

run sonar:
  stage: quality
  image: adoptopenjdk/openjdk11:alpine-jre
  before_script:
    - apk add nodejs npm
  script:
    - npm run sonarqube
  cache:
    paths:
      - /var/cache/apk/
      - /root/.sonar
  variables:
    SONARQUBE_URL: $SONAR_HOST_URL
    SONARQUBE_TOKEN: $SONAR_LOGIN
    SONARQUBE_ORGANIZATION: $SONAR_ORGANIZATION
    SONARQUBE_PROJECTKEY: $SONAR_PROJECTKEY

next minor:
  stage: version
  script:
    - echo 1

next release:
  stage: version
  script:
    - echo 1

build package:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/resources/main/static/
  only:
    - master

build image:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - PACKAGE_VERSION=$(sed -nr 's/^\s*\"version": "([0-9]{1,}\.[0-9]{1,}.*)",$/\1/p' package.json)
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"username\":\"$DOCKER_USER\",\"password\":\"$DOCKER_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/Dockerfile --destination $DOCKER_REGISTRY/$DOCKER_IMAGE:$PACKAGE_VERSION --destination $DOCKER_REGISTRY/$DOCKER_IMAGE:latest

deploy production:
  stage: deploy
  script:
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  only:
    - master

deploy staging:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - staging

deploy branch:
  stage: deploy
  script:
    - echo 1
