
image: node:alpine

stages:
  - prepare
  - test
  - version
  - build
  - deploy

install packages:
  stage: prepare
  script:
    - echo 1

run linter:
  stage: test
  script:
    - echo 1

run tests:
  stage: test
  script:
    - echo 1

execute coverage:
  stage: test
  script:
    - echo 1

run sonar:
  stage: test
  script:
    - echo 1

next minor:
  stage: version
  script:
    - echo 1

next release:
  stage: version
  script:
    - echo 1

build package:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build image:
  stage: build
  script:
    - echo 1

deploy production:
  stage: deploy
  image: ruby:alpine
  script:
    - apk update 
    - apk add ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master
  skip_cleanup: true

deploy staging:
  stage: deploy
  image: ruby:alpine
  script:
    - apk update 
    - apk add ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - staging

deploy branch:
  stage: deploy
  script:
    - echo 1
