
image: node:alpine

stages:
  - prepare
  - test
  - quality
  - version
  - build
  - deploy

install packages:
  stage: prepare
  script:
    - npm install
  cache:
    paths:
      - node_modules/

run tests:
  stage: test
  script:
    - npm run test

run sonar:
  stage: quality
  image: adoptopenjdk/openjdk11:alpine-jre
  before_script:
    - apk add nodejs npm
  script:
    - npm run sonarqube
  cache:
    paths:
      - /var/cache/apk/
      - /root/.sonar
  variables:
    SONARQUBE_URL: $SONAR_HOST_URL
    SONARQUBE_TOKEN: $SONAR_LOGIN
    SONARQUBE_ORGANIZATION: $SONAR_ORGANIZATION
    SONARQUBE_PROJECTKEY: $SONAR_PROJECTKEY

next minor:
  stage: version
  script:
    - echo 1

next release:
  stage: version
  script:
    - echo 1

build package:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

build image:
  stage: build
  script:
    - echo 1

deploy production:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master

deploy staging:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - staging

deploy branch:
  stage: deploy
  script:
    - echo 1
